import Head from "next/head";
import Image from "next/image";
import logo from "../static/logo.PNG";
import Link from "next/link";
import useSWR from "swr";

// import Image from "next/image";
import styles from "../styles/styles.module.css";
import ProductList from "./api/components/ProductList";

const fetcher = (url) => fetch(url).then((res) => res.json());

export default function Home() {
  const { data, error } = useSWR("/api/staticdata", fetcher);
  if (error) return <div>Failed to load</div>;

  if (!data) return <div>Loading...</div>;
  let obj = JSON.parse(data);
  return (
    <div className={styles.container}>
      <div>
        <h1>My Framework from file</h1>
        <ul>
          {/* <li>Name: {obj[0].serial}</li>
          <li>Language: {console.log(typeof data)}</li> */}

          {obj.map((obj) => (
            <li key={obj.id}>{obj.serial}</li>
          ))}

          {/* <ProductList products={products} /> */}
        </ul>
      </div>
      <Head>
        <title>Domin</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.login__container}>
        <header>
          <Image
            src={logo}
            alt="Domin Logo"
            width={75}
            height={75}
            className={styles.login__image}
          />
          <h1 className={styles.login__title}>DOMIN</h1>
          <h2 className={styles.login__subtitle}>ASCEND</h2>
        </header>
        <div>
          <p className={styles.login__description}>
            Connect to all your Domin Products
          </p>

          <div className={styles.grid}>
            Configure and access data from your<br></br> devices remotely, in a
            secure manner
          </div>
        </div>
        <div className={styles["login__button__wrapper"]}>
          <Link
            className={
              styles["login__button"] + " " + styles["login__button--blue"]
            }
            href="/_dashboard"
          >
            Get Started
          </Link>
          <Link
            className={
              styles["login__button"] + " " + styles["login__button--gray"]
            }
            href="/_dashboard"
          >
            Log In
          </Link>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
